apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-registry
  name: kube-registry
spec:
  ports:
  - name: kube-registry
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31112
  selector:
    app: kube-registry
  type: NodePort
