apiVersion: v1
kind: Service
metadata:
  name: docker-registry-ui
  labels:
    app: docker-registry-ui
    release: docker-registry-ui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      nodePort: 31114
      name: http
  selector:
      app: docker-registry-ui
      release: docker-registry-ui

